### ISSUE TITLE
Missing first hook.Remove argument for serialize command, causing it to constantly fail to remove itself

### ISSUE THREAD

**Issue by Andrew-Eathan** [Fasteroid/ulx-custom-fasteroid#6]
![image](https://github.com/Fasteroid/ulx-custom-fasteroid/assets/42521608/93593cc7-c3f0-4b47-b6fe-81da4e4043b0)
you forgot to add Think as the first argument at line 787, for some reason default gmod hook doesnt complain, but i noticed this because DLib actually checks the arguments and throws errors in console

**Comment by Fasteroid** [comment]
![image](https://github.com/Fasteroid/ulx-custom-fasteroid/assets/29342750/9651a34d-a028-491d-a2a8-c360164bb838)
No code permalink?

**Comment by Fasteroid** [comment]
> you forgot to add Think as the first argument at line 787, for some reason default gmod hook doesnt complain, but i noticed this because DLib actually checks the arguments and throws errors in console

And you forgot to pull `main` before opening your issue 😋
